FROM python:3.9.12

WORKDIR /REST_APIs

ADD ./REST_APIs/apis ./apis

COPY ./REST_APIs/api.py .
COPY ./REST_APIs/oriondb.py .
COPY ./REST_APIs/requirements.txt .
COPY user.py ../
COPY db.py ../
COPY keycloak_requests ../

RUN pip --no-cache-dir install -r requirements.txt

CMD ["python3", "api.py"]