version: "3.8"
services:
  app:
    build: .
    container_name: pre-processing
    environment:
      - ES_USERNAME=${ES_USERNAME}
      - ES_PASSWORD=${ES_PASSWORD}
      - ES_INDEX=${ES_INDEX}
      - ES_DATA_START_TIME=${ES_DATA_START_TIME}
      - ES_DATA_END_TIME=${ES_DATA_END_TIME}
      - ES_URL=${ES_URL}
      - POLLING_INTERVAL=${POLLING_INTERVAL}
      - AFTER_PRE_PROCESSING_URL=${AFTER_PRE_PROCESSING_URL}
      - STATIC_MODE=${STATIC_MODE}
      - CONFIG_FILE_PATH=${CONFIG_FILE_PATH}
      - STATIC_DATA_FILE_PATH=${STATIC_DATA_FILE_PATH}
    ports:
      - "5001:5000"
    restart: always
    volumes:
      - ./app:/app

