# Use an official Python runtime as a parent image
FROM python:3.9.12-alpine

# Set the working directory in the container
WORKDIR /dff

COPY ./ES_alert_system/ ./ES_alert_system/  
# Assuming you have this file ready


# Start Alert
CMD ["python3", "./ES_alert_system/main.py"]


