#!/bin/bash
#
#  Command Line Interface to start all DFF backend services
#

set -e

if (( $# != 1 )); then
    echo "Illegal number of parameters"
    echo "usage: services [create|start|stop]"
    exit 1
fi

loadData () {
        waitForMongo
        addDatabaseIndex
        waitForOrion
        echo ""
}

stoppingContainers () {
        echo "Stopping containers"
        docker-compose --log-level ERROR -f docker-compose-services.yml down -v --remove-orphans
}

displayServices () {
        echo ""
        docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" --filter name=dff-*
        echo ""
}

addDatabaseIndex () {
        printf "Adding appropriate \033[1mMongoDB\033[0m indexes for \033[1;34mOrion\033[0m  ..."
        docker exec  db-mongo mongo --eval '
        conn = new Mongo();db.createCollection("orion");
        db = conn.getDB("orion");
        db.createCollection("entities");
        db.entities.createIndex({"_id.servicePath": 1, "_id.id": 1, "_id.type": 1}, {unique: true});
        db.entities.createIndex({"_id.type": 1});
        db.entities.createIndex({"_id.id": 1});' > /dev/null

        docker exec  db-mongo mongo --eval '
        conn = new Mongo();db.createCollection("orion-openiot");
        db = conn.getDB("orion-openiot");
        db.createCollection("entities");
        db.entities.createIndex({"_id.servicePath": 1, "_id.id": 1, "_id.type": 1}, {unique: true});
        db.entities.createIndex({"_id.type": 1});
        db.entities.createIndex({"_id.id": 1});' > /dev/null
        echo -e " \033[1;32mdone\033[0m"
}

waitForMongo () {
        echo -e "\n⏳ Waiting for \033[1mMongoDB\033[0m to be available\n"
        while ! [ `docker inspect --format='{{.State.Health.Status}}' dff-mongo` == "healthy" ]
        do
                sleep 1
        done
}

waitForOrion () {
        echo -e "\n⏳ Waiting for \033[1;34mOrion\033[0m to be available\n"

        while ! [ `docker inspect --format='{{.State.Health.Status}}' dff-orion` == "healthy" ]
        do
          echo -e "Context Broker HTTP state: " `curl -s -o /dev/null -w %{http_code} 'http://localhost:1026/version'` " (waiting for 200)"
          sleep 1
        done
}

command="$1"
case "${command}" in
        "help")
        echo "usage: services [create|start|stop]"
        ;;
         "start")
                stoppingContainers
                echo -e "Starting seven containers \033[1;34mOrion\033[0m, \033[1;34mQuantumLeap\033[0m, \033[1mCrateDB\033[0m and \033[1mMongoDB\033[0m databases and a \033[1mRedis\033[0m cache, along with \033[0mKeycloak\033[0m and \033[0mpostgres-db\033[0m."
                echo -e "- \033[1;34mOrion\033[0m is the context broker"
                echo -e "- \033[1;34mQuantumLeap\033[0m will write to CrateDB"
                echo -e "- \033[1mKeycloak\033[0m is the Identity Manager"
                echo -e "- \033[1;36mKeycloak\033[0m will write to postgres-db"
                echo ""
                docker-compose --log-level ERROR -f docker-compose-services.yml up -d --remove-orphans
                displayServices
                ;;
        "stop")
                export $(cat .env | grep "#" -v)
                stoppingContainers
                ;;
        "create")
                export $(cat .env | grep "#" -v)
                echo "Pulling Docker images"
                docker-compose --log-level ERROR -p fiware pull
                ;;
        *)
                echo "Command not Found."
                echo "usage: services [create|start|stop]"
                exit 127;
                ;;
esac