pipeline {
    agent any
    environment {
      VM_DEV01 = "tcp://10.10.10.13:2375"
    }

    stages {
        stage('Clean up') {
            steps {
                script {
                    docker.withServer("$VM_DEV01") {    
                        echo 'Stopping old containers...'
                        sh 'docker-compose down'
                        echo 'Removing old containers...'
                        sh 'docker rm $(docker ps -a -q --filter="name=dff-app-keycloak") || true'
                        sh 'docker rm $(docker ps -a -q --filter="name=dff-api-keycloak") || true'
                        sh 'docker rm $(docker ps -a -q --filter="name=dff-login-keycloak") || true'
                        sh 'docker rm $(docker ps -a -q --filter="name=keycloak") || true'
                        sh 'docker rm $(docker ps -a -q --filter="name=kc-postgres") || true'
                    }
                }
            }
        }
        stage('Configure client_secret in client_secrets.json'){
            steps {
                sh """sed -i -e 's#CLIENT_SECRET_VALUE#$KEYCLOAK_SECRET#' ./client_secrets.json"""
            }
        }
        stage('Build images') {
            steps {
                echo 'Starting to build docker images'
                script {
                    docker.withServer("$VM_DEV01") {    
                        sh "docker-compose build"
                    }
                }
            }
        }
        stage('Deploy containers') {
            steps {
                script {
                    docker.withServer("$VM_DEV01") {
                        echo 'Deploy images to VM'
                        sh "docker-compose up -d"
                    }
                }
            }
        }
    }
}
